# Project

## Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import LocalOutlierFactor
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Dataset

In [ ]:
data= pd.read_csv("train.csv")
data_test = pd.read_csv("test.csv")

In [ ]:
data_test

ID   n0        n1        n2        n3        n4        n5        n6  n7  \
0      0  0.0  0.000000  0.908889  0.251257  0.662262  0.042495  0.000000   0   
1      1  0.0  0.000000  1.191055  0.407350  0.441898  0.000000  0.334858   0   
2      2  0.0  0.261903  0.992782  0.301102  0.636006  0.009558  0.009448   0   
3      3  0.0  0.000000  1.352401  0.346003  0.401412  0.000000  0.000000   0   
4      4  0.0  0.000000  1.114281  0.696140  0.121505  0.000000  0.000000   0   
..   ...  ...       ...       ...       ...       ...       ...       ...  ..   
410  410  0.0  0.000000  1.066927  0.495523  0.020179  0.010377  0.000000   0   
411  411  0.0  0.000000  1.044428  0.630166  0.214812  0.000000  0.297711   0   
412  412  0.0  0.000000  1.524889  0.000000  0.791997  0.000000  0.000000   0   
413  413  0.0  0.000000  1.066159  0.809718  0.601291  0.000000  0.000000   0   
414  414  0.0  0.235139  1.058271  0.327235  0.801501  0.000000  0.000000   0   

           n8  ...     n4086     n4087     n4088     n4089     n4090  \
0    0.964784  ...  0.694072  1.146161  1.483842  0.717836  0.472616   
1    0.295357  ...  0.273436  1.466932  0.940850  0.470344  1.032085   
2    0.974949  ...  0.000000  0.769983  0.834360  0.369656  1.000858   
3    0.450667  ...  0.339935  1.325595  0.981124  0.486731  0.747392   
4    0.591384  ...  0.093661  0.875113  0.360689  0.659230  0.546044   
..        ...  ...       ...       ...       ...       ...       ...   
410  0.190290  ...  0.182461  2.003547  0.602592  0.296488  0.673558   
411  0.992859  ...  0.000000  0.836084  1.055142  0.272300  1.213401   
412  0.070156  ...  0.269538  1.565473  0.857422  0.642805  0.870113   
413  0.728140  ...  0.407508  0.740154  0.947700  0.000000  0.625964   
414  1.372816  ...  0.373050  0.369727  1.159917  0.287697  0.846405   

        n4091     n4092  n4093  n4094     n4095  
0    0.000000  0.488022    0.0    0.0  0.655670  
1    0.000000  0.654070    0.0    0.0  0.614493  
2    0.431571  0.361993    0.0    0.0  0.392158  
3    0.000000  0.300671    0.0    0.0  0.628365  
4    0.000000  0.427255    0.0    0.0  0.835671  
..        ...       ...    ...    ...       ...  
410  0.000000  0.287565    0.0    0.0  0.595830  
411  0.106611  0.494905    0.0    0.0  0.321924  
412  0.134546  0.150362    0.0    0.0  0.724412  
413  0.000000  0.013839    0.0    0.0  0.367881  
414  0.315870  0.000000    0.0    0.0  0.347072  

[415 rows x 4097 columns]

In [ ]:
arr = data.to_numpy()
arr_test = data_test.to_numpy()
deleted=0
arr_aug = arr
for i in range(arr.shape[0]):
    if(np.any(arr[i]!=arr[i])):
        arr_aug = np.delete(arr_aug,i-deleted,axis=0)
        deleted+=1
arr=arr_aug

In [ ]:
Y_train = (arr.T[-1]).T
X= (arr.T[1:-1].T)
X_test= (arr_test.T[1:].T)

In [ ]:
unique=[]
sum=0
for i in Y_train:
    if(i not in unique):
        unique.append(i)
        sum+=1
sum

20

In [ ]:
unique

['Orange_Ripe',
 'Banana_Ripe',
 'Mango_Raw',
 'Leeche_Raw',
 'Mango_Ripe',
 'Papaya_Ripe',
 'Guava_Ripe',
 'Apple_Ripe',
 'Pomengranate_Ripe',
 'Guava_Raw',
 'Strawberry_Raw',
 'Apple_Raw',
 'Leeche_Ripe',
 'Papaya_Raw',
 'Strawberry_Ripe',
 'Pomengranate_Raw',
 'Coconut_Ripe',
 'Banana_Raw',
 'Coconut_Raw',
 'Orange_Raw']

In [ ]:
X.shape

(1216, 4096)

## Clustering

In [ ]:
X1 = np.vstack((X,X_test))

In [ ]:
kmeans = KMeans(n_clusters=sum, random_state=0, n_init="auto").fit(X1)

In [ ]:
clusters = np.array(kmeans.fit_predict(X1))

In [ ]:
clusters.shape

(1631,)

## One-Hot Encoding

In [ ]:
X1[X.shape[0],:]

array([0.0, 0.0, 0.908888996, ..., 0.0, 0.0, 0.655670345], dtype=object)

In [ ]:
X1_aug= np.zeros((X1.shape[0],X1.shape[1]+20))
for i in range(X1.shape[0]):
    X1_aug[i,:X1.shape[1]] = X1[i]
    X1_aug[i,X1.shape[1]+clusters[i]] = 10

In [ ]:
X1 = X1_aug

In [ ]:
X = X1[:X.shape[0],:]

In [ ]:
X_train = X

In [ ]:
X_test = X1[X.shape[0]:,:]

## LDA

In [ ]:
Y_train= [unique.index(Y_train[i]) for i in range(len(Y_train))]
Y_train = np.array(Y_train)

In [ ]:
X_train[30].shape

(4116,)

In [ ]:
X_train.shape

(1216, 4116)

In [ ]:
clf = LinearDiscriminantAnalysis(n_components=10)
clf.fit(X_train, Y_train)

LinearDiscriminantAnalysis(n_components=10)

In [ ]:
X_train = clf.transform(X_train)
X_test = clf.transform(X_test)

## Outlier Detection and Removal

In [ ]:
clf = LocalOutlierFactor(n_neighbors=25)
clf.fit(X_train)

LocalOutlierFactor(n_neighbors=25)

In [ ]:
outliers = clf.fit_predict(X_train)
outliers.shape

(1216,)

In [ ]:
X_aug = X_train
Y_aug = np.array(Y_train)
Y_aug.reshape((-1,1))
delete =0
for i in range(X_train.shape[0]):
    if(outliers[i]==-1):
        X_aug = np.delete(X_aug,i-delete,axis=0)
        Y_aug = np.delete(Y_aug,i-delete,axis=0)
        delete+=1

In [ ]:
X_train=X_aug

In [ ]:
Y_train = Y_aug

In [ ]:
Y_train = Y_train.reshape((-1,1))

## Multiclass Regression

In [ ]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        Dense(10, activation = 'relu',   name = "L1"),
        Dense(20, activation = 'softmax', name = "L2")
    ]
)

In [ ]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.01),
)

model.fit(
    X_train,Y_train,
    epochs=200
) 

Epoch 1/200
31/31 [==============================] - 1s 2ms/step - loss: 2.3129
Epoch 2/200
31/31 [==============================] - 0s 2ms/step - loss: 0.4635
Epoch 3/200
31/31 [==============================] - 0s 2ms/step - loss: 0.1455
Epoch 4/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0496
Epoch 5/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0247
Epoch 6/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0157
Epoch 7/200
31/31 [==============================] - 0s 3ms/step - loss: 0.0112
Epoch 8/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0083
Epoch 9/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0065
Epoch 10/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 11/200
31/31 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 12/200
31/31 [==============================] - 0s 3ms/step - loss: 0.0036
Epoch 13/200
31/31 [=================

In [ ]:
Y_predict = model.predict(X_test)

13/13 [==============================] - 0s 2ms/step


In [ ]:
X_test[3]

array([-38.29973619,   2.59730102,  11.56851881, -18.43243656,
        14.82342484,  10.83131155,  12.36713774,   2.32931453,
         8.19601905,   9.02529689])

In [ ]:
list(Y_predict[2]).index(np.max(Y_predict[2]))

6

In [ ]:
final = np.empty((Y_predict.shape[0],2),dtype='object')
for i in range(Y_predict.shape[0]):
  final[i,0] = i
  final[i,1] =  unique[list(Y_predict[i]).index(np.max(Y_predict[i]))]

In [ ]:
final

array([[0, 'Orange_Raw'],
       [1, 'Orange_Ripe'],
       [2, 'Guava_Ripe'],
       [3, 'Orange_Ripe'],
       [4, 'Pomengranate_Raw'],
       [5, 'Banana_Raw'],
       [6, 'Leeche_Ripe'],
       [7, 'Orange_Ripe'],
       [8, 'Mango_Ripe'],
       [9, 'Banana_Ripe'],
       [10, 'Strawberry_Raw'],
       [11, 'Coconut_Ripe'],
       [12, 'Papaya_Ripe'],
       [13, 'Mango_Raw'],
       [14, 'Guava_Ripe'],
       [15, 'Leeche_Raw'],
       [16, 'Orange_Raw'],
       [17, 'Strawberry_Raw'],
       [18, 'Mango_Ripe'],
       [19, 'Mango_Raw'],
       [20, 'Coconut_Raw'],
       [21, 'Orange_Ripe'],
       [22, 'Mango_Ripe'],
       [23, 'Pomengranate_Ripe'],
       [24, 'Papaya_Ripe'],
       [25, 'Mango_Raw'],
       [26, 'Papaya_Raw'],
       [27, 'Mango_Ripe'],
       [28, 'Coconut_Raw'],
       [29, 'Coconut_Raw'],
       [30, 'Banana_Ripe'],
       [31, 'Pomengranate_Raw'],
       [32, 'Banana_Ripe'],
       [33, 'Guava_Ripe'],
       [34, 'Apple_Raw'],
       [35, 'Mango_Ripe'],


In [ ]:
df = pd.DataFrame(final, columns = ['ID','Category'])

In [ ]:
df.to_csv('a1.csv')